---
- name: Create the binary-type map
  ansible.builtin.set_fact:
    # map the machine CPU type to the matching filename component
    cockroachdb_binary_arch:
      aarch64: arm64
      x86_64: amd64

- name: Check that tarball exists
  stat:
    path: /root/{{ cockroachdb_bin_prefix }}{{ cockroachdb_version }}.linux-{{ cockroachdb_binary_arch[ansible_architecture] }}.tgz
  register: _stat_result


- when: cockroachdb_version != "master" and not _stat_result.stat.exists
  block:
    - name: get cockroach binary
      get_url:
        url: '{{ cockroachdb_repo_url }}/{{ cockroachdb_bin_prefix }}{{ cockroachdb_version }}.linux-{{ cockroachdb_binary_arch[ansible_architecture] }}.tgz'
        dest: /root

    - name: untar the tar.gz
      unarchive:
        src: /root/{{ cockroachdb_bin_prefix }}{{ cockroachdb_version }}.linux-{{ cockroachdb_binary_arch[ansible_architecture] }}.tgz
        dest: /root
        remote_src: yes

    - name: Find unarchived cockroachdb directory
      find:
        paths:
          - "/root"
        patterns: "{{ cockroachdb_bin_prefix }}*.linux-{{ cockroachdb_binary_arch[ansible_architecture] }}"
        recurse: no
        file_type: directory
      register: dirs

    - name: copy binary to bin dir
      copy:
        src: "{{ dirs.files[0].path }}/cockroach"
        dest: /usr/local/bin/
        remote_src: yes
        mode: "0755"

    - name: copy GIS libs to right location
      copy:
        src: "{{ dirs.files[0].path }}/lib/{{ item }}"
        dest: /usr/local/lib/cockroach/
        remote_src: yes
      loop:
        - libgeos.so
        - libgeos_c.so

    - name: Recursively remove directory
      ansible.builtin.file:
        path: "{{ dirs.files[0].path }}"
        state: absent

- when: cockroachdb_version == "master"
  block:
    - ansible.builtin.shell: |
        wget https://edge-binaries.cockroachdb.com/cockroach/cockroach.linux-gnu-{{ cockroachdb_binary_arch[ansible_architecture] }}.LATEST
        chmod +x cockroach.linux-gnu-{{ cockroachdb_binary_arch[ansible_architecture] }}.LATEST
        mv cockroach.linux-gnu-{{ cockroachdb_binary_arch[ansible_architecture] }}.LATEST /usr/local/bin/cockroach
