---
- name: restart cockroachdb service
  ansible.builtin.systemd:
    name: cockroachdb
    state: restarted
    enabled: yes
    daemon_reload: yes

# TODO review security group for port 26257
- name: Init Cluster
  shell: |
    cockroach init \
    {{ (cockroachdb_secure) | ternary(cockroachdb_secure_flag, cockroachdb_insecure_flag) }} \
    --host={{ cockroachdb_join[0] }}:{{ cockroachdb_port }}
  register: result
  failed_when: result.rc != 0 and 'cluster has already been initialized' not in result.stderr and 'unable to bootstrap due to internal error' not in result.stderr


