---
- name: Recursively remove directory
  ansible.builtin.file:
    path: "{{ certificates_dir }}"
    state: absent

- name: Create a directory if it does not exist
  ansible.builtin.file:
    path: "{{ certificates_dir }}"
    state: directory
    mode: "0755"
 
# Step 1. Create the CA key and certificate pair
- name: Create a directory if it does not exist
  ansible.builtin.file:
    path: "{{ certificates_dir }}/{{ item }}"
    state: directory
    mode: "0755"
  loop:
    - certs
    - my-safe-directory

- name: Set ca.cnf
  ansible.builtin.template:
    src: ca.cnf.j2
    dest: "{{ certificates_dir }}/ca.cnf"

- name: create the CA key pair
  ansible.builtin.shell: |
    openssl genrsa \
      -out {{ certificates_dir }}/my-safe-directory/ca.key 2048
    chmod 400 {{ certificates_dir }}/my-safe-directory/ca.key
    openssl req \
      -new \
      -x509 \
      -config {{ certificates_dir }}/ca.cnf \
      -key {{ certificates_dir }}/my-safe-directory/ca.key \
      -out {{ certificates_dir }}/certs/ca.crt \
      -days 365 \
      -batch
    rm -f {{ certificates_dir }}/index.txt {{ certificates_dir }}/serial.txt
    touch {{ certificates_dir }}/index.txt
    echo '01' > {{ certificates_dir }}/serial.txt

# Step 2. Create the certificate and key pairs for nodes
- name: Create ca.cnf for each node
  ansible.builtin.template:
    src: node.cnf.j2
    dest: "{{ certificates_dir }}/node.{{ item }}.cnf"
  loop: "{{ certificates_hosts }}"

- name: create nodes key pair
  ansible.builtin.shell: |
    openssl genrsa \
      -out {{ certificates_dir }}/certs/node.{{ item }}.key 2048
    chmod 400 {{ certificates_dir }}/certs/node.{{ item }}.key
  loop: "{{ certificates_hosts }}"

- name: create nodes certificate
  ansible.builtin.shell: |
    openssl req \
      -new \
      -config {{ certificates_dir }}/node.{{ item }}.cnf \
      -key {{ certificates_dir }}/certs/node.{{ item }}.key \
      -out {{ certificates_dir }}/node.{{ item }}.csr \
      -batch

    openssl ca \
      -config {{ certificates_dir }}/ca.cnf \
      -keyfile {{ certificates_dir }}/my-safe-directory/ca.key \
      -cert {{ certificates_dir }}/certs/ca.crt \
      -policy signing_policy \
      -extensions signing_node_req \
      -out {{ certificates_dir }}/certs/node.{{ item }}.crt \
      -outdir {{ certificates_dir }}/certs/ \
      -in {{ certificates_dir }}/node.{{ item }}.csr \
      -batch
  loop: "{{ certificates_hosts }}"

# Step 3. Create the certificate and key pair for the root user
- name: Create client.cnf for root
  ansible.builtin.template:
    src: client.cnf.j2
    dest: "{{ certificates_dir }}/client.{{ item }}.cnf"
  loop: "{{ certificates_usernames }}"

- name: create client key pair
  ansible.builtin.shell: |
    openssl genrsa \
      -out {{ certificates_dir }}/certs/client.{{ item }}.key 2048

    chmod 400 {{ certificates_dir }}/certs/client.{{ item }}.key
  loop: "{{ certificates_usernames }}"


- name: create client certificates
  ansible.builtin.shell: |
    openssl req \
      -new \
      -config {{ certificates_dir }}/client.{{ item }}.cnf \
      -key {{ certificates_dir }}/certs/client.{{ item }}.key \
      -out {{ certificates_dir }}/client.{{ item }}.csr \
      -batch

    openssl ca \
      -config {{ certificates_dir }}/ca.cnf \
      -keyfile {{ certificates_dir }}/my-safe-directory/ca.key \
      -cert {{ certificates_dir }}/certs/ca.crt \
      -policy signing_policy \
      -extensions signing_client_req \
      -out {{ certificates_dir }}/certs/client.{{ item }}.crt \
      -outdir {{ certificates_dir }}/certs/ \
      -in {{ certificates_dir }}/client.{{ item }}.csr \
      -batch
  loop: "{{ certificates_usernames }}"
