---
- name: get list of current VMs via the count_tag
  shell: |
    az vm list \
    --resource-group "{{ azure_resource_group }}" \
    --show-details \ 
    --query "[?tags.deployment_id=='{{ deployment_id }}']" \
    --output json
  register: _vms

- name: Wait for SSH to come up
  wait_for:
    host: "{{ item.publicIps }}"
    port: 22
    timeout: 360
    sleep: 5
    state: started
  loop: "{{ _vms.stdout | from_json |json_query('[*]') }}"

- name: add instances to inventory groups
  add_host:
    name: "{{ item.publicIps }}"
    groups: "{{ item.tags.ansible_inv_groups.split(',') + [item.tags.ansible_cluster_name] }}"
    cluster_name: "{{ item.tags.ansible_cluster_name }}"
    cloud: azure
    region: "{{ item.tags.region }}"
    zone: "{{ item.tags.zone }}"
    ansible_user: "{{ item.tags.ansible_user }}"
    extra_vars: "{{ item.tags.extra_vars | from_json }}"
    
    public_hostname: "{{ item.fqdns }}"
    public_ip: "{{ item.publicIps }}"
    private_hostname: "{{ item.privateIps }}"
    private_ip: "{{ item.privateIps }}"

  loop: "{{ _vms.stdout | from_json |json_query('[*]') }}"
